name: Simple Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  script: |
                      sudo rm -f /var/www/html/index.html

                      mkdir -p ~/temp-repo
                      cd ~/temp-repo
                      if [ ! -d .git ]; then rm -rf *; git clone https://github.com/${{ github.repository }}.git .; else git pull; fi

                      sudo cp index.html /var/www/html/index.html
                      sudo chown www-data:www-data /var/www/html/index.html
                      sudo chmod 644 /var/www/html/index.html

                      sudo nginx -t && sudo systemctl reload nginx

                      rm -rf ~/temp-repo
